NguyenHiepNguyen_Asm2/KhongPhaiTuBanRazorPage/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace KhongPhaiTuBanRazorPage.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        public string LayoutName { get; set; }

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        public IActionResult OnPostLogout()
        {
            HttpContext.Session.Clear();
            return RedirectToPage("/Index");
        }
    }
}

NguyenHiepNguyen_Asm2/KhongPhaiTuBanRazorPage/Pages/Shared/_AdminLayout.cshtml
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="/Index">FUHotel</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="/Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/customers">Customer Management</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/bookingReservations">Booking Management</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/roominfomations">Room Management</a>
                    </li>
                    <li class="nav-item">
                        <form method="post" asp-page-handler="/Logout">
                            <button class="dropdown-item btn-action" type="submit">Đăng xuất</button>
                        </form>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

NguyenHiepNguyen_Asm2/KhongPhaiTuBanRazorPage/Pages/Shared/_CustomerLayout.cshtml
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="/Index">FUHotel</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="/Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Customers/Details">Thông tin cá nhân</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/BookingReservations/Index">Đặt phòng</a>
                    </li>
                    <li class="nav-item">
                        <form method="post" asp-page="/Index" asp-page-handler="Logout">
                            <button class="dropdown-item btn-action" type="submit">Đăng xuất</button>
                        </form>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

NguyenHiepNguyen_Asm2/KhongPhaiTuBanRazorPage/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["Title"] - FUHotel</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/chatStyle.css"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/microsoft-signalr/5.0.11/signalr.min.js"></script>
</head>
<body>
    @{
        string headerName = ViewData["HeaderName"]?.ToString() ?? "_NotAuthLayout";
    }

    @Html.Partial(headerName + ".cshtml")

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <button class="open-button" onclick="openForm()">Open Chat</button>

    <div class="form-popup" id="myForm">
        <div class="message-list-container">
            <ul id="messageList"></ul>
        </div>
        <form class="form-container" id="chatForm">
            <h1>Chat</h1>
            <label for="msg"><b>Message</b></label>
            <textarea id="messageInput" placeholder="Type message.." name="msg" required></textarea>
            <button type="button" id="sendButton" class="btn">Send</button>
            <button type="button" class="btn cancel" onclick="closeForm()">Close</button>
        </form>
    </div>

    @RenderSection("Scripts", required: false)
    <script src="~/js/Chat.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
</body>
</html>

NguyenHiepNguyen_Asm2/KhongPhaiTuBanRazorPage/Pages/Shared/_NotAuthLayout.cshtml
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="/Index">FUHotel</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="/Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/About">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Login">Login</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>